FileVersion = 1
LastConfig = "Debug"
LastPlatform = "Win32"
RecentFilesList = ["src\\Interfaces\\IPlayerInfo.bf", "SamplePlugin\\src\\SamplePlugin.bf", "src\\SourceBeefAPI.bf", "Disassembly", "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\String.bf", "src\\Interfaces\\IVEngineServer.bf", "src\\Interfaces\\IPlayerInfoManager.bf", "src\\Math.bf", "src\\CServerPlugin.bf", "Disassembly", "Disassembly", "Disassembly", "Disassembly", "Disassembly", "Disassembly", "Disassembly", "Disassembly", "Disassembly", "Disassembly", "Disassembly"]

[MainWindow]
X = 0
Y = 0
Width = 1200
Height = 1024
ShowKind = "Maximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 333.0
RequestedHeight = 487.0
SizePriority = 487.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 293.0
RequestedHeight = 583.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 115.0
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
RequestedWidth = 1918.0
RequestedHeight = 64.0
SizePriority = 1918.0
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "String.bf"
TabWidth = 89.0
Type = "SourceViewPanel"
FilePath = "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\String.bf"
CursorPos = 8915
VertPos = 4290.0
ProjectName = "corlib"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "IPlayerInfo.bf"
TabWidth = 115.0
Type = "SourceViewPanel"
FilePath = "src\\Interfaces\\IPlayerInfo.bf"
CursorPos = 235
VertPos = 1530.0
ProjectName = "SourceBeef"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Math.bf"
TabWidth = 85.0
Type = "SourceViewPanel"
FilePath = "src\\Math.bf"
CursorPos = 86
ProjectName = "SourceBeef"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Disassembly"
TabWidth = 112.0
Type = "DisassemblyPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "SourceBeefAPI.bf"
TabWidth = 138.0
Type = "SourceViewPanel"
FilePath = "src\\SourceBeefAPI.bf"
CursorPos = 2204
VertPos = 1590.0
ProjectName = "SourceBeef"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "IPlayerInfoManager.bf"
TabWidth = 157.0
Type = "SourceViewPanel"
FilePath = "src\\Interfaces\\IPlayerInfoManager.bf"
CursorPos = 311
ProjectName = "SourceBeef"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "IVEngineServer.bf"
TabWidth = 131.0
Type = "SourceViewPanel"
FilePath = "src\\Interfaces\\IVEngineServer.bf"
CursorPos = 68
ProjectName = "SourceBeef"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "SamplePlugin.bf"
TabWidth = 123.0
Type = "SourceViewPanel"
FilePath = "SamplePlugin\\src\\SamplePlugin.bf"
CursorPos = 929
VertPos = 135.0
ProjectName = "SamplePlugin"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "CServerPlugin.bf"
TabWidth = 125.0
Type = "SourceViewPanel"
FilePath = "src\\CServerPlugin.bf"
CursorPos = 1608
VertPos = 450.0
ProjectName = "SourceBeef"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 318.0
RequestedHeight = 356.4
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 318.0
RequestedHeight = 188.0
SizePriority = 0.5594369
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Breakpoints"
TabWidth = 118.0
Type = "BreakpointPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 86.0
Type = "WatchPanel"
Columns = [{Width = 200.0}, {Width = 182.0}, {Width = 200.0}]
Items = ["eax", "ecx", ""]

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Memory"
TabWidth = 99.0
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 343.0

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Modules"
TabWidth = 101.0
Type = "ModulePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Class View"
TabWidth = 111.0
Type = "ClassViewPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 1594.0
RequestedHeight = 188.0
SizePriority = 0.4405631
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 97.0
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 105.0
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 111.0
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 90.0
Type = "OutputPanel"

[[Breakpoints]]
File = "src\\SamplePlugin.bf"
Line = 6
Column = 3

[[Breakpoints]]
Symbol = "-main"

[[Breakpoints]]
File = "src\\Interfaces\\IGameEventListener.bf"
Line = 5
Column = 2

[[Breakpoints]]
File = "src\\Interfaces\\IGameEventManager.bf"
Line = 13
Column = 4

[[Breakpoints]]
File = "src\\Interfaces\\IGameEventManager.bf"
Line = 15
Column = 2

[[Breakpoints]]
File = "src\\Interfaces\\IGameEventManager.bf"
Line = 14
Column = 4

[[Breakpoints]]
File = "src\\Interfaces\\IPlayerInfo.bf"
Line = 15
Column = 3

[[Breakpoints]]
File = "SamplePlugin\\src\\SamplePlugin.bf"
Line = 34
Column = 4

[[Breakpoints]]
File = "SamplePlugin\\src\\SamplePlugin.bf"
Line = 36
Column = 4

[DebuggerDisplayTypes.""]
IntDisplayType = "Hexadecimal"
