FileVersion = 1
Projects = {SourceBeef = {Path = "."}, SamplePlugin = {Path = "SamplePlugin"}, InterfaceGenTest = {Path = "InterfaceGenTest"}}

[Workspace]
StartupProject = "InterfaceGenTest"

[Configs.Debug.Win32]
BfOptimizationLevel = "Og"
