FileVersion = 1
LastConfig = "Debug"
LastPlatform = "Win32"
RecentFilesList = ["SamplePlugin\\src\\SamplePlugin.bf", "src\\Interfaces\\IGameEventListener.bf", "src\\Tier0.bf", "Disassembly", "src\\Interfaces\\IGameEventManager.bf", "src\\SourceBeefAPI.bf", "src\\Interfaces\\IGameEvent.bf", "Disassembly", "Disassembly", "Disassembly", "Disassembly", "Disassembly", "Disassembly", "Disassembly", "Disassembly", "Disassembly", "Disassembly", "Disassembly", "Disassembly"]

[MainWindow]
X = 0
Y = 0
Width = 1200
Height = 1024
ShowKind = "Maximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 299.0
RequestedHeight = 487.0
SizePriority = 487.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 383.0
RequestedHeight = 644.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 115.0
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
RequestedWidth = 1918.0
RequestedHeight = 64.0
SizePriority = 1918.0
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "IGameEvent.bf"
TabWidth = 123.0
Type = "SourceViewPanel"
FilePath = "src\\Interfaces\\IGameEvent.bf"
CursorPos = 1025
VertPos = 225.0
ProjectName = "SourceBeef"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Disassembly"
TabWidth = 122.0
Type = "DisassemblyPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Tier0.bf"
TabWidth = 74.0
Type = "SourceViewPanel"
FilePath = "src\\Tier0.bf"
CursorPos = 417
ProjectName = "SourceBeef"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "IGameEventListener.bf"
TabWidth = 157.0
Type = "SourceViewPanel"
FilePath = "src\\Interfaces\\IGameEventListener.bf"
CursorPos = 1333
VertPos = 45.0
ProjectName = "SourceBeef"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "SamplePlugin.bf"
TabWidth = 123.0
Type = "SourceViewPanel"
FilePath = "SamplePlugin\\src\\SamplePlugin.bf"
CursorPos = 1351
VertPos = 585.0
ProjectName = "SamplePlugin"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "IGameEventManager.bf"
TabWidth = 165.0
Type = "SourceViewPanel"
FilePath = "src\\Interfaces\\IGameEventManager.bf"
CursorPos = 420
ProjectName = "SourceBeef"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "SourceBeefAPI.bf"
TabWidth = 128.0
Type = "SourceViewPanel"
FilePath = "src\\SourceBeefAPI.bf"
CursorPos = 2687
VertPos = 1350.0
ProjectName = "SourceBeef"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 318.0
RequestedHeight = 307.6
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 318.0
RequestedHeight = 188.0
SizePriority = 0.5594369
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Breakpoints"
TabWidth = 118.0
Type = "BreakpointPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Watch"
TabWidth = 86.0
Type = "WatchPanel"
Columns = [{Width = 200.0}, {Width = 182.0}, {Width = 200.0}]
Items = ["eax", "ecx", "0x78DF60A3", ""]

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 99.0
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 343.0

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Modules"
TabWidth = 101.0
Type = "ModulePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Class View"
TabWidth = 111.0
Type = "ClassViewPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 1594.0
RequestedHeight = 188.0
SizePriority = 0.4405631
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Find Results"
TabWidth = 119.0
Type = "FindResultsPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 97.0
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 105.0
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 111.0
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 90.0
Type = "OutputPanel"

[[Breakpoints]]
File = "src\\Interfaces\\IGameEventListener.bf"
Line = 61
Column = 9

[DebuggerDisplayTypes.""]
IntDisplayType = "Hexadecimal"
