FileVersion = 1
LastConfig = "Debug"
LastPlatform = "Win32"
RecentFilesList = ["InterfaceGenTest\\src\\Program.bf", "src\\SDK\\Shared\\Enums\\PluginResult.bf", "src\\Tier0.bf", "src\\CServerPlugin.bf", "src\\SDK\\CSGO\\Interface\\IServerPluginCallbacks.bf", "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\Int.bf", "Disassembly", "Disassembly", "Disassembly", "Disassembly", "Disassembly", "Disassembly", "Disassembly", "Disassembly", "Disassembly", "Disassembly"]

[MainWindow]
X = 1360
Y = 210
Width = 1200
Height = 1024
ShowKind = "Maximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 299.0
RequestedHeight = 487.0
SizePriority = 487.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 294.0
RequestedHeight = 644.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 115.0
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
RequestedWidth = 1918.0
RequestedHeight = 64.0
SizePriority = 1918.0
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Program.bf"
TabWidth = 96.0
Type = "SourceViewPanel"
FilePath = "InterfaceGenTest\\src\\Program.bf"
CursorPos = 779
VertPos = 480.0
ProjectName = "InterfaceGenTest"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "PluginResult.bf"
TabWidth = 115.0
Type = "SourceViewPanel"
FilePath = "src\\SDK\\Shared\\Enums\\PluginResult.bf"
CursorPos = 189
ProjectName = "SourceBeef"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
RequestedWidth = 2262.0
RequestedHeight = 879.0
SizePriority = 2262.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "CServerPlugin.bf"
TabWidth = 125.0
Type = "SourceViewPanel"
FilePath = "src\\CServerPlugin.bf"
CursorPos = 272
VertPos = 60.0
ProjectName = "SourceBeef"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 318.0
RequestedHeight = 457.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 318.0
RequestedHeight = 188.0
SizePriority = 0.6110243
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Auto Watches"
TabWidth = 130.0
Type = "AutoWatchPanel"
Columns = [{Width = 288.0}, {Width = 661.0}, {Width = 200.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Errors"
TabWidth = 86.0
Type = "ErrorsPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Breakpoints"
TabWidth = 118.0
Type = "BreakpointPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 86.0
Type = "WatchPanel"
Columns = [{Width = 200.0}, {Width = 182.0}, {Width = 200.0}]
Items = ["eax", "ecx", "0x78DF60A3", ""]

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 99.0
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 343.0

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Modules"
TabWidth = 101.0
Type = "ModulePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Class View"
TabWidth = 111.0
Type = "ClassViewPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 1594.0
RequestedHeight = 188.0
SizePriority = 0.3889757
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Find Results"
TabWidth = 119.0
Type = "FindResultsPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 97.0
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 105.0
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 111.0
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 90.0
Type = "OutputPanel"

[[Breakpoints]]
File = "src\\Interfaces\\IGameEventListener.bf"
Line = 61
Column = 9

[[Breakpoints]]
File = "src\\CServerPlugin.bf"
Line = 60
Column = 3

[[Breakpoints]]
File = "src\\SourceBeefAPI.bf"
Line = 70
Column = 3

[[Breakpoints]]
File = "SamplePlugin\\src\\SamplePlugin.bf"
Line = 17
Column = 3

[[Breakpoints]]
File = "SamplePlugin\\src\\SamplePlugin.bf"
Line = 70
Column = 3

[[Breakpoints]]
File = "src\\CServerPlugin.bf"
Line = 29
Column = 3

[DebuggerDisplayTypes."System.Collections.List<uint8>.[]"]
IntDisplayType = "Hexadecimal"

[DebuggerDisplayTypes.""]
IntDisplayType = "Decimal"
